package tam;

/**
 * This enum provides a list of all the user interface
 * text that needs to be loaded from the XML properties
 * file. By simply changing the XML file we could initialize
 * this application such that all UI controls are provided
 * in another language.
 * 
 * @author Richard McKenna
 * @co-author Jason Lyan
 * @version 1.0
 */
public enum TAManagerProp {
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE LABELS FOR ALL TABS
    CLEAR_BUTTON_TEXT,
    ADD_OR_UPDATE_BUTTON_TEXT,
    
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    TA_DATA_TEXT,
    TAS_HEADER_TEXT,
    UNDERGRAD_COLUMN_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    UPDATE_TA_TEXT,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    START_TIME_TEXT,
    END_TIME_TEXT,
    CHANGE_HOURS_TEXT,
    
    // THESE ARE FOR COURSE DETAILS WORKSPACE
    COURSE_DETAILS_TEXT,
    COURSE_INFO_TEXT,
    CD_SUBJECT_TEXT,
    CD_NUMBER_TEXT,
    CD_SEMESTER_TEXT,
    CD_YEAR_TEXT,
    CD_TITLE_TEXT,
    CD_INSTRUCTOR_NAME_TEXT,
    CD_INSTRUCTOR_HOME_TEXT,
    CD_EXPORT_DIR_TEXT,
    CD_CHANGE_BUTTON_TEXT,
    CD_SITE_TEMPLATE_TEXT,
    CD_SITE_TEMPLATE_DESCRIPTION_TEXT,
    CD_TEMPLATE_DIRECTORY_BUTTON_TEXT,
    CD_SITE_PAGES_TEXT,
    CD_USE_COLUMN_TEXT,
    CD_NAVBAR_TITLE_COLUMN_TEXT,
    CD_FILE_NAME_COLUMN_TEXT,
    CD_SCRIPT_COLUMN_TEXT,
    CD_PAGE_STYLE_TEXT,
    CD_BANNER_SCHOOL_IMAGE_TEXT,
    CD_LEFT_FOOTER_IMAGE_TEXT,
    CD_RIGHT_FOOTER_IMAGE_TEXT,
    CD_STYLESHEET_TEXT,
    CD_PAGE_STYLE_NOTE_TEXT,
    
    // THESE ARE FOR RECITATION DATA WORKSPACE
    RECITATION_DATA_TEXT,
    RECITATIONS_TEXT,
    RECITATIONS_BUTTON_TEXT,
    REC_SECTION_COLUMN_TEXT,
    REC_INSTRUCTOR_COLUMN_TEXT,
    REC_DAY_OR_TIME_COLUMN_TEXT,
    REC_LOCATION_COLUMN_TEXT,
    REC_TA_COLUMN_TEXT,
    REC_ADD_OR_EDIT_TEXT,
    REC_SECTION_TEXT,
    REC_INSTRUCTOR_TEXT,
    REC_DAY_OR_TIME_TEXT,
    REC_LOCATION_TEXT,
    REC_SUPERVISING_TA_TEXT,
    
    // THESE ARE FOR SCHEDULE DATA WORKSPACE
    SCHEDULE_DATA_TEXT,
    SCHEDULE_TEXT,
    SCHED_CALENDAR_BOUNDARIES_TEXT,
    SCHED_STARTING_MONDAY_TEXT,
    SCHED_ENDING_FRIDAY_TEXT,
    SCHEDULE_ITEMS_TEXT,
    SCHED_BUTTON_TEXT,
    SCHED_TYPE_COLUMN_TEXT,
    SCHED_DATE_COLUMN_TEXT,
    SCHED_TITLE_COLUMN_TEXT,
    SCHED_TOPIC_COLUMN_TEXT,
    SCHED_ADD_OR_EDIT_TEXT,
    SCHED_TYPE_TEXT,
    SCHED_DATE_TEXT,
    SCHED_TIME_TEXT,
    SCHED_TITLE_TEXT,
    SCHED_TOPIC_TEXT,
    SCHED_LINK_TEXT,
    SCHED_CRITERIA_TEXT,
    
    // THESE ARE FOR PROJECT DATA WORKSPACE
    PROJECT_DATA_TEXT,
    PROJECTS_TEXT,
    PROJ_TEAMS_TEXT,
    PROJ_BUTTON_TEXT,
    PROJ_NAME_COLUMN_TEXT,
    PROJ_COLOR_COLUMN_TEXT,
    PROJ_TEXT_COLOR_COLUMN_TEXT,
    PROJ_LINK_COLUMN_TEXT,
    PROJ_ADD_OR_EDIT_TEXT,
    PROJ_NAME_TEXT,
    PROJ_COLOR_TEXT,
    PROJ_TEXT_COLOR_TEXT,
    PROJ_LINK_TEXT,
    PROJ_STUDENTS_TEXT,
    PROJ_FIRST_NAME_COLUMN_TEXT,
    PROJ_LAST_NAME_COLUMN_TEXT,
    PROJ_TEAM_COLUMN_TEXT,
    PROJ_ROLE_COLUMN_TEXT,
    PROJ_FIRST_NAME_TEXT,
    PROJ_LAST_NAME_TEXT,
    PROJ_TEAM_TEXT,
    PROJ_ROLE_TEXT,
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    TA_EMAIL_NOT_PROPER_TITLE,
    TA_EMAIL_NOT_PROPER_MESSAGE,
    OFFICE_HOURS_INVALID_TITLE,
    OFFICE_HOURS_INVALID_MESSAGE,
    OFFICE_HOURS_CHANGE_CONFIRMATION_TITLE,
    OFFICE_HOURS_CHANGE_CONFIRMATION_MESSAGE
}
